### PR TITLE
WorkerPool remove `#[wasm_bindgen]` usage

### PR DESCRIPTION
**Pull request by Slixe**
~~Set the WASM bindgen on WorkerPool behind a feature `workerpool-bindgen` disabled by default.~~

Delete the `#[wasm_bindgen]` usage on WorkerPool.

See issue #18

### CODE REVIEW

**Comment by Slixe** [comment]
@temeddix is it ok like this? Or you want it enabled by default to keep the current behavior?

**Comment by temeddix** [comment]
I believe it's okay to remove the bindings completely, because this library focuses on running Rust code relying on `tokio` on browsers.

What do you think?

**Comment by temeddix** [comment]
I will test the changes locally as soon as possible :)

**Comment by Slixe** [comment]
> I believe it's okay to remove the bindings completely, because this library focuses on running Rust code relying on `tokio` on browsers.
> 
> What do you think?

I'm fully for it, but I thought for some reasons you would like to keep it

**Comment by Slixe** [comment]
okay done, anything else @temeddix ?

**Comment by temeddix** [comment]
Looks good to me!

**Pull request merged**
